/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controller;
import Modelo.Producto;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zipaf
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelRegistrar = new javax.swing.JPanel();
        LabelNombreRegistrar = new javax.swing.JLabel();
        BntGuardarRegistrar = new javax.swing.JButton();
        TFCantidadRegistrar = new javax.swing.JTextField();
        LabelCantidadRegistrar = new javax.swing.JLabel();
        LabelPrecioRegistrar = new javax.swing.JLabel();
        LabelCategoriaRegistrar = new javax.swing.JLabel();
        TFNombreRegistrar = new javax.swing.JTextField();
        TFPrecioRegistrar = new javax.swing.JTextField();
        CBCategoriaRegistrar = new javax.swing.JComboBox<>();
        PanelConsultar = new javax.swing.JPanel();
        LabelNombreConsultar = new javax.swing.JLabel();
        LabelCantidadConsultar = new javax.swing.JLabel();
        LabelPrecioConsultar = new javax.swing.JLabel();
        LabelCategoriaConsultar = new javax.swing.JLabel();
        LabelIdConsultar = new javax.swing.JLabel();
        TFIdConsultar = new javax.swing.JTextField();
        TFNombreConsultar = new javax.swing.JTextField();
        TFCantidadConsultar = new javax.swing.JTextField();
        TFPrecioConsultar = new javax.swing.JTextField();
        BntEliminarConsultar = new javax.swing.JButton();
        BntConsultarConsultar = new javax.swing.JButton();
        BntActualizarConsultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaConsultar = new javax.swing.JTable();
        CBCategoriaConsultar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);

        PanelRegistrar.setBackground(new java.awt.Color(204, 204, 255));

        LabelNombreRegistrar.setBackground(new java.awt.Color(255, 204, 102));
        LabelNombreRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelNombreRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNombreRegistrar.setText("Nombre");
        LabelNombreRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelNombreRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelNombreRegistrar.setOpaque(true);

        BntGuardarRegistrar.setBackground(new java.awt.Color(255, 153, 0));
        BntGuardarRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BntGuardarRegistrar.setText("Guardar");
        BntGuardarRegistrar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BntGuardarRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntGuardarRegistrarActionPerformed(evt);
            }
        });

        TFCantidadRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCantidadRegistrarActionPerformed(evt);
            }
        });

        LabelCantidadRegistrar.setBackground(new java.awt.Color(255, 204, 102));
        LabelCantidadRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelCantidadRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCantidadRegistrar.setText("Cantidad");
        LabelCantidadRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelCantidadRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelCantidadRegistrar.setOpaque(true);

        LabelPrecioRegistrar.setBackground(new java.awt.Color(255, 204, 102));
        LabelPrecioRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelPrecioRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPrecioRegistrar.setText("Precio");
        LabelPrecioRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelPrecioRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelPrecioRegistrar.setOpaque(true);

        LabelCategoriaRegistrar.setBackground(new java.awt.Color(255, 204, 102));
        LabelCategoriaRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelCategoriaRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCategoriaRegistrar.setText("Categoria");
        LabelCategoriaRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelCategoriaRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelCategoriaRegistrar.setOpaque(true);

        TFNombreRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombreRegistrarActionPerformed(evt);
            }
        });

        TFPrecioRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPrecioRegistrarActionPerformed(evt);
            }
        });

        CBCategoriaRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CBCategoriaRegistrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "VIVERES" }));
        CBCategoriaRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCategoriaRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
        PanelRegistrar.setLayout(PanelRegistrarLayout);
        PanelRegistrarLayout.setHorizontalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCantidadRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNombreRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPrecioRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCategoriaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNombreRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TFCantidadRegistrar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CBCategoriaRegistrar, javax.swing.GroupLayout.Alignment.LEADING, 0, 144, Short.MAX_VALUE)
                        .addComponent(TFPrecioRegistrar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BntGuardarRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        PanelRegistrarLayout.setVerticalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFNombreRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCantidadRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFCantidadRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrecioRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFPrecioRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCategoriaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBCategoriaRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(BntGuardarRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Registrar", PanelRegistrar);

        PanelConsultar.setBackground(new java.awt.Color(204, 204, 255));

        LabelNombreConsultar.setBackground(new java.awt.Color(255, 204, 102));
        LabelNombreConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelNombreConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNombreConsultar.setText("Nombre");
        LabelNombreConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelNombreConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelNombreConsultar.setOpaque(true);

        LabelCantidadConsultar.setBackground(new java.awt.Color(255, 204, 102));
        LabelCantidadConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelCantidadConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCantidadConsultar.setText("Cantidad");
        LabelCantidadConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelCantidadConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelCantidadConsultar.setOpaque(true);

        LabelPrecioConsultar.setBackground(new java.awt.Color(255, 204, 102));
        LabelPrecioConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelPrecioConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPrecioConsultar.setText("Precio");
        LabelPrecioConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelPrecioConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelPrecioConsultar.setOpaque(true);

        LabelCategoriaConsultar.setBackground(new java.awt.Color(255, 204, 102));
        LabelCategoriaConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelCategoriaConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCategoriaConsultar.setText("Categoria");
        LabelCategoriaConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelCategoriaConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelCategoriaConsultar.setOpaque(true);

        LabelIdConsultar.setBackground(new java.awt.Color(255, 204, 102));
        LabelIdConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelIdConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelIdConsultar.setText("Id");
        LabelIdConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LabelIdConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LabelIdConsultar.setOpaque(true);

        TFIdConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIdConsultarActionPerformed(evt);
            }
        });

        TFNombreConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombreConsultarActionPerformed(evt);
            }
        });

        TFCantidadConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCantidadConsultarActionPerformed(evt);
            }
        });

        TFPrecioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPrecioConsultarActionPerformed(evt);
            }
        });

        BntEliminarConsultar.setBackground(new java.awt.Color(255, 153, 0));
        BntEliminarConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BntEliminarConsultar.setText("Eliminar");
        BntEliminarConsultar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BntEliminarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntEliminarConsultarActionPerformed(evt);
            }
        });

        BntConsultarConsultar.setBackground(new java.awt.Color(255, 153, 0));
        BntConsultarConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BntConsultarConsultar.setText("Consultar");
        BntConsultarConsultar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BntConsultarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntConsultarConsultarActionPerformed(evt);
            }
        });

        BntActualizarConsultar.setBackground(new java.awt.Color(255, 153, 0));
        BntActualizarConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BntActualizarConsultar.setText("Actualizar");
        BntActualizarConsultar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BntActualizarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntActualizarConsultarActionPerformed(evt);
            }
        });

        TablaConsultar.setBackground(new java.awt.Color(255, 204, 102));
        TablaConsultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablaConsultar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TablaConsultar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Categoria", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaConsultar.setGridColor(new java.awt.Color(204, 204, 204));
        TablaConsultar.setSelectionBackground(new java.awt.Color(255, 255, 102));
        TablaConsultar.setSelectionForeground(new java.awt.Color(255, 0, 0));
        TablaConsultar.setShowGrid(true);
        TablaConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConsultarMouseClicked(evt);
            }
        });
        TablaConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaConsultarKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TablaConsultar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );

        CBCategoriaConsultar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CBCategoriaConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "VIVERES" }));
        CBCategoriaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCategoriaConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConsultarLayout = new javax.swing.GroupLayout(PanelConsultar);
        PanelConsultar.setLayout(PanelConsultarLayout);
        PanelConsultarLayout.setHorizontalGroup(
            PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelIdConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LabelPrecioConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelNombreConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelCantidadConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelCategoriaConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConsultarLayout.createSequentialGroup()
                        .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelConsultarLayout.createSequentialGroup()
                                .addComponent(TFNombreConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addComponent(BntEliminarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLayout.createSequentialGroup()
                                .addComponent(TFPrecioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BntActualizarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLayout.createSequentialGroup()
                                .addComponent(TFCantidadConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BntConsultarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelConsultarLayout.createSequentialGroup()
                                .addComponent(TFIdConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(78, 78, 78))
                    .addGroup(PanelConsultarLayout.createSequentialGroup()
                        .addComponent(CBCategoriaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelConsultarLayout.setVerticalGroup(
            PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarLayout.createSequentialGroup()
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLayout.createSequentialGroup()
                        .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TFIdConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFNombreConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BntEliminarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelConsultarLayout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(LabelIdConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelNombreConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelConsultarLayout.createSequentialGroup()
                                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFCantidadConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BntConsultarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFPrecioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BntActualizarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLayout.createSequentialGroup()
                                .addComponent(LabelCantidadConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelPrecioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelConsultarLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCategoriaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBCategoriaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Consultar", PanelConsultar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFCantidadRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCantidadRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCantidadRegistrarActionPerformed

    private void TFNombreRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombreRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNombreRegistrarActionPerformed

    private void TFPrecioRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPrecioRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPrecioRegistrarActionPerformed

    private void BntGuardarRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntGuardarRegistrarActionPerformed
        if (!this.TFNombreRegistrar.getText().equals("") && !this.TFCantidadRegistrar.getText().equals("") && !this.TFPrecioRegistrar.getText().equals("")) {
            String nombre = this.TFNombreRegistrar.getText();
            int cantidad = Integer.valueOf(this.TFCantidadRegistrar.getText());
            double precio = Double.valueOf(this.TFPrecioRegistrar.getText());
            String categoria = this.CBCategoriaRegistrar.getSelectedItem().toString();

            try {
                Controller.registrarProducto(nombre, cantidad, categoria, precio);
                JOptionPane.showMessageDialog(null, "Registro guardado con éxito", "Nuevo Registro", JOptionPane.PLAIN_MESSAGE);
                this.TFNombreRegistrar.setText("");
                this.TFCantidadRegistrar.setText("");
                this.TFPrecioRegistrar.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se pudo guardar el registro", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese valores validos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BntGuardarRegistrarActionPerformed

    private void BntActualizarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntActualizarConsultarActionPerformed
        String idString = this.TFIdConsultar.getText();
        String nombre = this.TFNombreConsultar.getText();
        String cantidad = this.TFCantidadConsultar.getText();
        String categoria = this.CBCategoriaConsultar.getSelectedItem().toString();
        String precio = this.TFPrecioConsultar.getText();

        if (idString.length() == 0 || nombre.length() == 0 || cantidad.length() == 0 || precio.length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese valores validos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean existe = false;
            List<Producto> listaProductos = Controller.listarProductos();
            int id = Integer.valueOf(idString);
            for (int i = 0; i < listaProductos.size(); i++) {
                if (listaProductos.get(i).getId() == id) {
                    existe = true;
                    break;
                }
            }
            if (existe) {
                Controller.actualizarProducto(id, nombre, Integer.valueOf(cantidad), categoria, Double.valueOf(precio));
                JOptionPane.showMessageDialog(null, "Se ha actualizado el registro", "Actualizar", JOptionPane.PLAIN_MESSAGE);
                this.TFIdConsultar.setText("");
                this.TFNombreConsultar.setText("");
                this.TFCantidadConsultar.setText("");
                this.TFPrecioConsultar.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "El id ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BntActualizarConsultarActionPerformed

    private void BntConsultarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntConsultarConsultarActionPerformed
        String idString = this.TFIdConsultar.getText();
        DefaultTableModel modelo = (DefaultTableModel) this.TablaConsultar.getModel();
        modelo.setRowCount(0);
        List<Producto> listaProductos = Controller.listarProductos();

        if (idString.length() == 0) {
            for (int i = 0; i < listaProductos.size(); i++) {
                Producto p1 = listaProductos.get(i);
                modelo.insertRow(i, new Object[]{p1.getId(), p1.getNombre(), p1.getCategoria(), p1.getCantidad(), p1.getPrecio()});
            }
        } else {
            boolean existe = false;
            int id = Integer.valueOf(idString);

            for (int i = 0; i < listaProductos.size(); i++) {
                if (listaProductos.get(i).getId() == id) {
                    existe = true;
                    break;
                }
            }
            if (existe) {
                Producto p2 = Controller.obtenerProducto(id);
                modelo.insertRow(0, new Object[]{p2.getId(), p2.getNombre(), p2.getCategoria(), p2.getCantidad(), p2.getPrecio()});
            } else {
                JOptionPane.showMessageDialog(null, "El id ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BntConsultarConsultarActionPerformed

    private void BntEliminarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntEliminarConsultarActionPerformed
        String idString = this.TFIdConsultar.getText();

        if (idString.length() == 0) {
            JOptionPane.showMessageDialog(null, "No ha ingresado un id", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean existe = false;
            List<Producto> listaProductos = Controller.listarProductos();
            int id = Integer.valueOf(idString);
            for (int i = 0; i < listaProductos.size(); i++) {
                if (listaProductos.get(i).getId() == id) {
                    existe = true;
                    break;
                }
            }
            if (existe) {
                Controller.borrarProducto(id);
                JOptionPane.showMessageDialog(null, "Se ha eliminado el registro", "Eliminar", JOptionPane.PLAIN_MESSAGE);
                this.TFIdConsultar.setText("");
                this.TFNombreConsultar.setText("");
                this.TFCantidadConsultar.setText("");
                this.TFPrecioConsultar.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "El id ingresado no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BntEliminarConsultarActionPerformed

    private void TFPrecioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPrecioConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPrecioConsultarActionPerformed

    private void TFCantidadConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCantidadConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCantidadConsultarActionPerformed

    private void TFNombreConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombreConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNombreConsultarActionPerformed

    private void TFIdConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIdConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFIdConsultarActionPerformed

    private void CBCategoriaRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCategoriaRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCategoriaRegistrarActionPerformed

    private void TablaConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConsultarMouseClicked
        //// Otra forma de rellenar la tabla con los datos de la base de datos al momento de consultar
//        JTable table = (JTable) evt.getSource();
//        int fila = table.rowAtPoint(evt.getPoint());
//        DefaultTableModel modelo = (DefaultTableModel) this.TablaConsultar.getModel();
//
//        String id = String.valueOf(modelo.getValueAt(fila, 0));
//        String nombre = String.valueOf(modelo.getValueAt(fila, 1));
//        String categoria = String.valueOf(modelo.getValueAt(fila, 2));
//        String cantidad = String.valueOf(modelo.getValueAt(fila, 3));
//        String precio = String.valueOf(modelo.getValueAt(fila, 4));
//
//        this.TFIdConsultar.setText(id);
//        this.TFNombreConsultar.setText(nombre);
//        this.TFCantidadConsultar.setText(cantidad);
//        this.TFPrecioConsultar.setText(precio);
//        this.CBCategoriaConsultar.setSelectedItem(categoria);
        rellenarTabla();
    }//GEN-LAST:event_TablaConsultarMouseClicked

    private void CBCategoriaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCategoriaConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBCategoriaConsultarActionPerformed

    private void TablaConsultarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaConsultarKeyReleased
        rellenarTabla();
    }//GEN-LAST:event_TablaConsultarKeyReleased

    private void rellenarTabla() {

        int fila = this.TablaConsultar.getSelectedRow();

        if (this.TablaConsultar.getValueAt(fila, 0) == null) {
            JOptionPane.showMessageDialog(null, "No hay datos, presione consultar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String id = String.valueOf(this.TablaConsultar.getValueAt(fila, 0));
            String nombre = String.valueOf(this.TablaConsultar.getValueAt(fila, 1));
            String categoria = String.valueOf(this.TablaConsultar.getValueAt(fila, 2));
            String cantidad = String.valueOf(this.TablaConsultar.getValueAt(fila, 3));
            String precio = String.valueOf(this.TablaConsultar.getValueAt(fila, 4));
            
            this.TFIdConsultar.setText(id);
            this.TFNombreConsultar.setText(nombre);
            this.TFCantidadConsultar.setText(cantidad);
            this.TFPrecioConsultar.setText(precio);
            this.CBCategoriaConsultar.setSelectedItem(categoria);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntActualizarConsultar;
    private javax.swing.JButton BntConsultarConsultar;
    private javax.swing.JButton BntEliminarConsultar;
    private javax.swing.JButton BntGuardarRegistrar;
    private javax.swing.JComboBox<String> CBCategoriaConsultar;
    private javax.swing.JComboBox<String> CBCategoriaRegistrar;
    private javax.swing.JLabel LabelCantidadConsultar;
    private javax.swing.JLabel LabelCantidadRegistrar;
    private javax.swing.JLabel LabelCategoriaConsultar;
    private javax.swing.JLabel LabelCategoriaRegistrar;
    private javax.swing.JLabel LabelIdConsultar;
    private javax.swing.JLabel LabelNombreConsultar;
    private javax.swing.JLabel LabelNombreRegistrar;
    private javax.swing.JLabel LabelPrecioConsultar;
    private javax.swing.JLabel LabelPrecioRegistrar;
    private javax.swing.JPanel PanelConsultar;
    private javax.swing.JPanel PanelRegistrar;
    private javax.swing.JTextField TFCantidadConsultar;
    private javax.swing.JTextField TFCantidadRegistrar;
    private javax.swing.JTextField TFIdConsultar;
    private javax.swing.JTextField TFNombreConsultar;
    private javax.swing.JTextField TFNombreRegistrar;
    private javax.swing.JTextField TFPrecioConsultar;
    private javax.swing.JTextField TFPrecioRegistrar;
    private javax.swing.JTable TablaConsultar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
